version: '3.0'
services:

  express-stpd:
    build: server
    ports:
      - "3000:3000"
    container_name: express-stpd
    volumes:
      - ./server:/express
    restart: always

  nextjs-stpd:
    build: webapp-smart-toilet-paper
    ports:
      - "8080:3000"
    container_name: nextjs-stpd
    volumes:
      - ./webapp-smart-toilet-paper:/nextjs
    restart: always

